
spring:
  application:
    name: weather-forecast-service

server:
  port: 8080
  servlet:
    context-path: /forecasts

management:
  server:
    port: 8081
    servlet:
      context-path: /admin/forecasts
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    com.rubenjg.weatherforecastservice: DEBUG
