
spring:
  application:
    name: weather-forecast-service

server:
  port: 8080
  servlet:
    context-path: /forecasts

management:
  server:
    port: 8081
    servlet:
      context-path: /admin/forecasts
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

logging:
  level:
    root: INFO
    com.rubenjg.weatherforecastservice: DEBUG

service:
  open-weather-map:
    url:
    api-key: <insert-api-key-here>
